// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrjivzlnfpatqmlosnln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyaml2emxuZnBhdHFtbG9zbmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTg4NzgsImV4cCI6MjA3MDgzNDg3OH0.JzjsrJzBzYRrNPBiZZ9R5M07c5h66bha14CWy98-rx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});